name: "SpendingTracker"
services:
  # PostgreSQL DB
  spendingtracker_db:
    image: postgres:16
    container_name: spendingtracker_db
    environment:
      POSTGRES_PASSWORD: "docker1234"
      POSTGRES_USER: "docker_user"
      POSTGRES_DB: "spendingtracker_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker_user -d spendingtracker_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spendingtracker_network

  # Backend
  spendingtracker_backend:
    container_name: spendingtracker_backend
    depends_on:
      spendingtracker_db:
        condition: service_healthy
    build:
      context: "../backend"
      dockerfile: "../docker/backend_Dockerfile"
    environment:
      PORT: 8082
      APP_DIR: /workspace # mount to /workspace
    ports:
      - "8082:8082"
    volumes:
      - ../backend:/workspace # mount backend/ to /workspace
      - ./entrypoint-wrapper.sh:/entrypoint-wrapper.sh:ro
    working_dir: /workspace
    entrypoint: ["/bin/bash", "/entrypoint-wrapper.sh"]
    networks:
      spendingtracker_network:
        aliases:
          - spendingtracker-backend
    restart: unless-stopped

  # Frontend
  spendingtracker_frontend:
    container_name: spendingtracker_frontend
    depends_on:
      - spendingtracker_backend
    build:
      context: ../frontend
      dockerfile: ../docker/frontend_Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://spendingtracker-backend:8082
    networks:
      - spendingtracker_network

volumes:
  postgres_data:

networks:
  spendingtracker_network:
    driver: bridge
